### ISSUE TITLE
Conflict with twitter bootstrap class

### ISSUE THREAD

**Issue by RajRoR** [justinfrench/formtastic#1069]
Now, formtastic automatically adds a class named 'label' to input labels. https://github.com/justinfrench/formtastic/commit/d318815e6ed5907868e437c943ac3c0c2e38ce82#commitcomment-7455718

How I can avoid having 'label' as class for my all labels in semantic_form_for?

I am using bootstrap, so bootstrap defines 'label' class as:

``` css
.label {
  display: inline;
  padding: .25em .6em;
  font-size: 75%;
  font-weight: bold;
  line-height: 1;
  color: #ffffff;
  text-align: center;
  white-space: nowrap; 
  vertical-align: baseline;
  border-radius: .25em;
}
```

Now, as you can see, its making labels text WHITE. This is my problem. I just want to avoid having label class.
