### ISSUE TITLE
Make i18n keys for namespaced models consistent with recent Rails versions

### ISSUE THREAD

**Issue by dolzenko** [justinfrench/formtastic#445]
I've just upgraded to Rails 3.0.3 and it introduced the change so that keys for namespaced models are now nested instead of being just separated by `/`. Better illustrated with example:

before for model `Messaging::Conversation` you had

```
en:
  activemodel:
    models:
      messaging/conversation:
        one: Conversation
        other: Conversations
```

now you need

```
en:
  activemodel:
    models:
      messaging:
        conversation:
          one: Conversation
          other: Conversations
```

I think formtastic should be consistent with that change.
