### ISSUE TITLE
i18n for buttons

### ISSUE THREAD

**Issue by sevenseacat** [justinfrench/formtastic#847]
Using Formtastic 2.2.0.

I know the readme says it should be possible to configure i18n for buttons using:

```
en:
  formtastic:
    actions:
      create: 'My text'
```

However this simply doesn't seem to work. Neither does nesting the `create` key under a model name. 

If I use a named key, eg `create_foo` and then reference it in my view `f.action :submit, label: :create_foo` it works, but no other method seems to.
