### ISSUE TITLE
Formtastic::UnknownActionError

### ISSUE THREAD

**Issue by diangy** [justinfrench/formtastic#871]
I am getting a Formtastic::UnknownActionError whenever I use this code:

``` ruby
= f.actions :save, :submit
```

or even

``` ruby
= f.actions do
  = f.action :save
  = f.action :submit
```

However my I18n file has those actions:

``` yaml
en:
  hello: "Hello world"
  formtastic:
    actions:
      save: "Save & Return Later"
      submit: "Submit to CTSI for review"
```

The former f.buttons format worked perfectly.
