### ISSUE TITLE
When nested object is namespaced, i18n key is invalid ("namespaced" too)

### ISSUE THREAD

**Issue by stevo** [justinfrench/formtastic#900]
i.e.

Shop::Project has_many Shop::Products

instead of looking for

```
en: 
 formtastic:
  labels:
   project:
    product:
```

it will look for

```
en: 
 formtastic:
  labels:
   project:
    shop/product: 
```

Probably changing 

`model_name, nested_model_name  = normalize_model_name(self.model_name.underscore)`

to

`model_name, nested_model_name  = normalize_model_name(self.model_name.demodulize.underscore)`

should solve the problem
