### ISSUE TITLE
Chrome displayes list-item on select fields

### ISSUE THREAD

**Issue by ghost** [justinfrench/formtastic#910]
Chrome (Version 24, OS: Linux) displayes list-item on select fields with standard formtastic css.
![List-item](https://f.cloud.github.com/assets/65235/62741/f2de5f50-5d60-11e2-82eb-9a492ace5a86.png)

Fixed with

``` css
li.select, li.date_select {
    list-style: none;
}
```
