### ISSUE TITLE
Localization scopes

### ISSUE THREAD

**Issue by jkthorne** [justinfrench/formtastic#926]
I am wondering if I can add a localization scope for a project that would set the input_html.
I see something that might sugest this is your specs.

something in config/locales/en.yaml

```
en:
  formtastic:
    posts:
      new:
        title:
          input_html:
            data: 
              stuff: stuff in here
```

can I add stuff to data with a custom scope?
