### ISSUE TITLE
I18n error

### ISSUE THREAD

**Issue by optimum-dulopin** [justinfrench/formtastic#934]
hi,
i'm trying to deal with I18n in formtastic

here my en.yml

en:
  activerecord:
    errors:
      models:
        annonce:
          attributes:
            ville:
              blank: must be filled

```
models:
  annonce: Classifieds
attributes:
  annonce:
    ville: City
```

for the form input, everything is fine
but if form is submit with no city, it displays this message
- Ville : must be filled

what to do so that "Ville" would be translated  ?
I was also searching how to change format message but I didnt succeed. It is possible to remove #{attribute} : 

thanks
